### ISSUE TITLE
Silently refresh access tokens in the background

### ISSUE THREAD

**Issue by DoruEC** [soofstad/react-oauth2-pkce#100]
Hello,

First of all, thanks for the library, saved me a lot of implementation time.

I have a question about refresh tokens.
In the features it said "Silently refreshes short-lived access tokens in the background", now, I know the callback "onRefreshTokenExpire" but on that one the only event that can be given is the login (which causes the app to go back and forth through the processes which results in page refresh).

Am I missing something that can be configured to actually silently refresh tokens (so the user does not get a page refresh) or I need to implement a custom function myself to obtain that?

Thanks in advance.

**Comment by sebastianvitterso** [comment]
When we say "Silently refreshes short-lived access tokens in the background", we're only talking about the access token, not the refresh token.

Auth0 has a [descriptive article](https://auth0.com/docs/secure/tokens/refresh-tokens) on the nature of refresh tokens, but in short: 
* You get both an access token and a refresh token. They both last for e.g. 15 minutes, or maybe the refresh token lasts for twice as long as the access token. 
* You send the access token to your api to authenticate that you are you.
* The refresh token is sent to the authentication server before the access token expires, and in return, the client receives a new access token (and possibly a new refresh token as well). 
* If the refresh token expires before the client has received a new one, then the client can no longer authenticate that they are who they say they are, and they will have to log in again.

The final bullet-point is the reason why we "only" give the login-function in the onRefreshTokenExpire-event. There is nothing else to do at this point.

But if you log in and look at your network traffic, you should - every now and again - see a request going out to your auth provider to refresh your access token (silently) in the background.

Does this help? If not, feel free to ask about whatever point I missed.

**Comment by sebastianvitterso** [comment]
That doesn't sound like the intended behaviour. It sounds like the refreshing of the access token isn't working right. Which auth-provider is this with? 

--- 

Here's a "quick test" you can do:
Go into browser devtools (I use Chrome), and open "Application". Then go to "Local Storage" and it should look something like this:
![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/4fe015e1-4aa2-4e5b-aea5-55b3f878173c)

Change `ROCP_tokenExpire` to some value in the past, I usually just set it to `2`.
![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/afe57f4b-0811-4fd7-81ef-0e2a6b7fee88)

Go into your network tab, and verify that (within the next minute or so) a request called "token" is sent to refresh your access token. It should look something like this:
![image](https://github.com/soofstad/react-oauth2-pkce/assets/37065184/52c22fc4-53b8-4a57-98b3-ceb3c803eb49)

If any of these things look different to you, let me know here.

**Comment by DoruEC** [comment]
@sebastianvitterso weird, I did the test exactly like that, having a valid refreshTokenExpire timestamp (not to be in the past) and expired accessToken before I actually wrote you that, but for sure I made something wrong as now re-doing again the tests it actually just goes to the token endpoint as intended.

Thank you so much for the fast response and clarification.
