### ISSUE TITLE
💡 [REQUEST] - Add ability to use the extraTokenParameters into fetchWithRefreshToken 

### ISSUE THREAD

**Issue by ShpakVl** [soofstad/react-oauth2-pkce#102]
### Summary

In my case, i need to pass same extra params into fetchTokens query, and on refetchToken. But with the current implementation of fetchWithRefreshToken function i can`t do it.
It will be great if you will add it.

### Basic Example

Code that i write to do it

```ts
export const fetchWithRefreshToken = (props: {
  config: TInternalConfig
  refreshToken: string
}): Promise<TTokenResponse> => {
  const { config, refreshToken } = props
  const refreshRequest: TTokenRequestForRefresh = {
    grant_type: 'refresh_token',
    refresh_token: refreshToken,
    scope: config.scope,
    client_id: config.clientId,
    redirect_uri: config.redirectUri,
    ...config.extraTokenParameters,
  }
  return postTokenRequest(config.tokenEndpoint, refreshRequest)
}
```

**Comment by soofstad** [comment]
Hi @ShpakVl 👋 
I agree, think we should implement this as you describe. 
Don't think there are any drawbacks really, and would be expected behaviour.
