### ISSUE TITLE
Bug: "Bad authorization state" after periods of inactivity

### ISSUE THREAD

**Issue by jeremy-ensemble** [soofstad/react-oauth2-pkce#114]
This was difficult to reproduce.  Still haven't determined if it's an interruption in connectivity, or when the user gets logged out.  However, sometimes I do not get a token or error from AuthContext.  I do see in the console there is this error "Bad authorization state. Refreshing the page might solve the issue."

This tends to happen when the page was either opened for awhile but not attended to.  And maybe even when the computer goes into sleep mode.  Still have not been able to find the exact steps to reproduce.

## The current behavior

There is no error returned from AuthContext.

## The expected behavior

An error should be returned from AuthContext

**Comment by soofstad** [comment]
Have you defined how to handle an expired refreshToken?
This can be done by passing a function to `onRefreshTokenExpire`.
For example like so;
```js
const authConfig: TAuthConfig = {
  clientId: 'myClientID',
  ...
  onRefreshTokenExpire: (event: TRefreshTokenExpiredEvent) => window.confirm('Session expired. Refresh page to continue using the site?') && event.login(),
}
```

Also, is your server responding with proper `expires_in` and `refresh_expires_in` values. If not, the library has no way of knowing when it should refresh the token, and might end up trying to refresh with an expired one.

You can use these config parameters to set this explicitly:

```js
  // Can be used if auth provider doesn't return access token expiration time in token response
  tokenExpiresIn?: number // default: null
  // Can be used if auth provider doesn't return refresh token expiration time in token response
  refreshTokenExpiresIn?: number // default: null
```

**Comment by jeremy-ensemble** [comment]
> Have you defined how to handle an expired refreshToken? This can be done by passing a function to `onRefreshTokenExpire`. For example like so;
> 
> ```js
> const authConfig: TAuthConfig = {
>   clientId: 'myClientID',
>   ...
>   onRefreshTokenExpire: (event: TRefreshTokenExpiredEvent) => window.confirm('Session expired. Refresh page to continue using the site?') && event.login(),
> }
> ```
> 
Yes, I am doing this, but without the prompt.

```
onRefreshTokenExpire: event.login()
```

> Also, is your server responding with proper `expires_in` and `refresh_expires_in` values. If not, the library has no way of knowing when it should refresh the token, and might end up trying to refresh with an expired one.
> 
> You can use these config parameters to set this explicitly:
> 
> ```js
>   // Can be used if auth provider doesn't return access token expiration time in token response
>   tokenExpiresIn?: number // default: null
>   // Can be used if auth provider doesn't return refresh token expiration time in token response
>   refreshTokenExpiresIn?: number // default: null
> ```

Thanks for letting me know.  I will need to investigate if `expires`_in and `refresh_expires_in` are coming back.  If they are not i will set accordingly.
