### ISSUE TITLE
Bug: rename "login" to "logIn"

### ISSUE THREAD

**Issue by getsnoopy** [soofstad/react-oauth2-pkce#115]
Function names should be in the imperative form, which means they should be verbs. Since the verb for the action is a compound verb, it's two words: *log* and *in*. In `camelCase`, this would be `logIn` (just as it is with its complementary function `logOut`), not `login` (which is the noun form).

**Comment by soofstad** [comment]
Your right! "Logout" is not a verb. Thanks for pointing this out :slightly_smiling_face: 

Agreed we should fix this (with backwards compatibility), so any PR is welcome.

**Comment by getsnoopy** [comment]
Sure, I'll get going on a PR for this.

**Comment by sebastianvitterso** [comment]
@getsnoopy Did you start working on a little PR for this?

**Comment by getsnoopy** [comment]
@sebastianvitterso I haven't yet; I'll probably get to it next week.
