### ISSUE TITLE
Bug: Not providing a scope results in "scope=undefined"

### ISSUE THREAD

**Issue by getsnoopy** [soofstad/react-oauth2-pkce#116]
## Steps To Reproduce

1. Configure an `AuthProvider` with a configuration that doesn't specify `scope` as a parameter.
2. Call `login()` to trigger the login process.
3. After logging in on the authentication provider side, monitor the request body of the token request. It will have a parameter of `scope` with the value `undefined`.

## The current behaviour
When a `scope` for the OAuth 2.0 request is not provided, the library makes a request to the server with the request body having `scope=undefined` as a parameter. Since this is a `application/x-www-form-urlencoded` request, the values of `scope` are treated as strings on the server side, which issues tokens for the `undefined` scope, which is wrong.

## The expected behaviour
The parameter shouldn't be in the body at all.

**Comment by soofstad** [comment]
Hi,
Thank you for reporting.
I'm unable to reproduce this, and as you can see  at https://github.com/soofstad/react-oauth2-pkce/blob/main/src/authentication.ts#L31, this should be protected against.

Are you sure you are using the latest verision?
If not, I will need some example code needed to reproduce the issue.
