### ISSUE TITLE
Bug: Not possible to change storageKeyPrefix to anything other than 'ROCP_'

### ISSUE THREAD

**Issue by vselleby** [soofstad/react-oauth2-pkce#119]
## Steps To Reproduce

const authConfig: TAuthConfig = {
  clientId: 'myClientID',
  authorizationEndpoint: 'https://myAuthProvider.com/auth',
  tokenEndpoint: 'https://myAuthProvider.com/token',
  redirectUri: 'http://localhost:3000/',
  scope: 'someScope openid',
  onRefreshTokenExpire: (event: TRefreshTokenExpiredEvent) => window.confirm('Session expired. Refresh page to continue using the site?') && event.login(),
  storageKeyPrefix: 'TEST_'
}

Does not work, it compiles with error: Type '"TEST_"' is not assignable to type '"ROCP_"'.

## The current behavior
Even though storageKeyPrefixis settable, it is only possible to assign it to "ROCP_"

## The expected behavior
It should be possible to set storageKeyPrefix to any string value.

**Comment by soofstad** [comment]
Hi,
Thank you for reporting :slightly_smiling_face: 
This is now fixed in v1.15.2

**Comment by aldesgroup** [comment]
Hi! Thanks for this good package!
It seems there's still a hardcoded "ROCP_" [here](https://github.com/soofstad/react-oauth2-pkce/blob/main/src/authentication.ts#L13), though it's probably not very harmful.
