### ISSUE TITLE
Bug: Nothing happens when using login() in Next.js

### ISSUE THREAD

**Issue by qr3n** [soofstad/react-oauth2-pkce#123]
## Steps To Reproduce

1. Create a Next.js project
2. Try using the library

## The current behavior
The function returns null

## The expected behavior
Redirect to authentication page

If anyone has a working example, please share. I'm new to Next.

**Comment by soofstad** [comment]
I can have a look at this discussion; https://github.com/soofstad/react-oauth2-pkce/discussions/90#discussioncomment-5902906.
I know people have gotten it to work in NextJS with this approach
