### ISSUE TITLE
💡 [REQUEST] - To refresh the access token without triggering login()

### ISSUE THREAD

**Issue by fgranda1** [soofstad/react-oauth2-pkce#124]
### Summary

the creation of an event method that allows to refresh the access token without triggering login() and not redirecting the user to the open if connect provider.

### Basic Example

I'm using an openId connect provider, I want to refresh the access token while the user is logged in without log the user out. I could show a popup window that advise the user that the token is almost expired and add a CTA to refresh the token before its expiration.

the POST request that my providers use for refreshing the token includes form data  keys:

grant_type: refresh_token
refresh_token: <refresh_ oken>
client_id:<client id>

it returns the access token, token_type, and expiration.

### Drawbacks

This feature could allow the user or dev to decide if wants to refresh the token or not before expiration, without forcing him to login again if wants to keep the session.

**Comment by soofstad** [comment]
Hi @fgranda1 :wave: 

If I understand your suggestion correctly, this is already supported.
It's listed in the list of features here; https://github.com/soofstad/react-oauth2-pkce#features (Silently refreshes short-lived access tokens in the background)

And if you are interested in the code, you can see its implementation here; https://github.com/soofstad/react-oauth2-pkce/blob/main/src/AuthContext.tsx#L179.

If this is not working for you, please elaborate :slightly_smiling_face:

**Comment by fgranda1** [comment]
> Hi @fgranda1 👋
> 
> If I understand your suggestion correctly, this is already supported. It's listed in the list of features here; https://github.com/soofstad/react-oauth2-pkce#features (Silently refreshes short-lived access tokens in the background)
> 
> And if you are interested in the code, you can see its implementation here; https://github.com/soofstad/react-oauth2-pkce/blob/main/src/AuthContext.tsx#L179.
> 
> If this is not working for you, please elaborate 🙂

Thanks for the clarification!
