### ISSUE TITLE
Bug: Fail to get token from a Spring Security server

### ISSUE THREAD

**Issue by andre-paris** [soofstad/react-oauth2-pkce#125]
I'm using a Spring Security server for authentication, the authorize and code callback works but when the client retrieves the token from the server, it gets a 401 Unauthorized. 

## Steps To Reproduce

1. Get a Spring Security server: https://github.com/eugenp/tutorials/tree/master/spring-security-modules/spring-security-pkce
2. Edit the `pkce-auth-server/src/main/java/com/baeldung/security/pkce/authserver/conf/AuthServerConfiguration.java` class with the redirect URI: `http://127.0.0.1:3000`
3. Run the authentication server with `mvn spring-boot::run`
4. Edit the `src/index.js` of this project to set the `authConfig` as follows:
````
const authConfig = {
  clientId: 'pkce-client',
  authorizationEndpoint: 'http://localhost:8085/oauth2/authorize',
  tokenEndpoint: 'http://localhost:8085/oauth2/token',
  logoutEndpoint: 'http://127.0.0.1:8081/logout',
  redirectUri: 'http://127.0.0.1:3000',
  onRefreshTokenExpire: (event) =>
    window.confirm('Tokens have expired. Refresh page to continue using the site?') && event.login(),
  decodeToken: true,
  scope: 'openid email',
  clearURL: true,
  autoLogin: false,
  storage: 'local',
}
````
When prompted for username/password, enter:
username: user
password: password

## The current behavior
The request to `ouath2/token` returns 401
![react-bug](https://github.com/soofstad/react-oauth2-pkce/assets/4292242/a58f7560-6b6a-48ef-bf77-733e2e0fca29)

## The expected behavior
The request to `oauth2/token` returns the Token

**Comment by sebastianvitterso** [comment]
If I'm understanding correctly, your issue is on the server side of this, not on the client side - meaning it's at [eugenp/tutorials](https://github.com/eugenp/tutorials/tree/master) you should make your issue, not here?

**Comment by andre-paris** [comment]
yes, the issue is on the server side, Spring Security is requiring to send a Basic authorization header to get the token, fixed by setting the user `client_authentication_methods` to `none`.
Thank you for the quick response and sorry for the inconvenience.
