### ISSUE TITLE
💡 [REQUEST] - Add ability to add headers to requests

### ISSUE THREAD

**Issue by jgornick** [soofstad/react-oauth2-pkce#128]
### Summary

Similar to adding extra parameters to all of the requests, it would be nice to have the ability to add additional HTTP headers as well. For example, some services require a base64 encoded Authorization header to be provided when getting a token. Even though this isn't "standard", there still seems to be a decent amount of services that implement this.

Granted the example here is for token headers, but this approach could be applied to all types of requests.

### Basic Example

```ts
const authConfig: TAuthConfig = {
  extraTokenHeaders: (headers, ...args) => {
    // inside of args includes configured and retrieved token information
    const [clientId, clientSecret] = args

    return {
      ...headers,
      Authorization: `Basic ${Buffer.from(`${clientId}:${clientSecret}`).toString('base64')}`,
  }
}
```

### Drawbacks

* The client is using the secret making it possible to get access to?

**Comment by soofstad** [comment]
Hi @jgornick 
First of all, you should never have a `clientSecret` in your web app. You should never even use "Basic" authentication :slightly_smiling_face: 

That a side, there could be some other valid cases where adding a custom header is needed, so I see how this could be useful :+1:

**Comment by anthony-vito** [comment]
If we do implement this, we should inspect the extra headers and if an "Authorization" header is provided print out a BIG WARNING that this is super super insecure and probably very wrong. PKCE OAuth Flow NEVER has an authorization header for very good reasons. ( or uses a client secret )

**Comment by jgornick** [comment]
Hey @soofstad! Thanks for responding so promptly!

> First of all, you should never have a clientSecret in your web app. You should never even use "Basic" authentication 🙂

Totally 😄 However, I'm using this for a private/personal project, so was going against best practices here.

> That a side, there could be some other valid cases where adding a custom header is needed, so I see how this could be useful 👍

Awesome! I'm happy to hear I wasn't too far off on the request!

**Comment by jgornick** [comment]
I didn't know if I should bring up this idea here or in another ticket, but does it make sense to even have the extra parameter options be a function with what parameters will be passed and other information that may be included (e.g., code, clientID)?

```ts
const authConfig: TAuthConfig = {
  extraTokenParameters: (parameters, args) => {
    // inside of args includes configured and retrieved token information
    const { clientId, code } = args

    return {
      ...parameters,
      foo: code + clientId
  }
}
```

**Comment by soofstad** [comment]
> I didn't know if I should bring up this idea here or in another ticket, but does it make sense to even have the extra parameter options be a function with what parameters will be passed and other information that may be included (e.g., code, clientID)?
> 
> ```ts
> const authConfig: TAuthConfig = {
>   extraTokenParameters: (parameters, args) => {
>     // inside of args includes configured and retrieved token information
>     const { clientId, code } = args
> 
>     return {
>       ...parameters,
>       foo: code + clientId
>   }
> }
> ```

Yes, this makes sense. Some of the extra parameters can sometimes be dynamic, so setting them static at runtime is not always possible. Have had this though a while, but never needed it myself.

Please make a separate feature request issue for this :)
