### ISSUE TITLE
Bug: Redirects replace instead of creating a history entry

### ISSUE THREAD

**Issue by getsnoopy** [soofstad/react-oauth2-pkce#134]
Whenever the `login` or `logOut` functions are called, the page from which those functions are called is replaced in the browser history with the URL where the user is being redirected.

## Steps To Reproduce

1. Call `login` or `logOut` from any page.

## The current behaviour
The browser history entry for the page from which the call is made is replaced.

## The expected behaviour
A new entry should be created for the URL to where the user is being redirected. If the user clicks the back button on that page, the user should come back to the page they were on (the one that they presumably clicked a button or what not from), not go back to the page before that page.

**Comment by sebastianvitterso** [comment]
Related: https://github.com/soofstad/react-oauth2-pkce/issues/97

@soofstad, now that you have more time on your hands, do you see any reasons why this shouldn't work?

**Comment by soofstad** [comment]
No. I've tested the old PR, and it seems to cause no issues.
Suggest we merge it.
