### ISSUE TITLE
💡 [REQUEST] - Refresh access token without resetting the refresh token

### ISSUE THREAD

**Issue by rning** [soofstad/react-oauth2-pkce#137]
### Summary

Hello, thank you for the convenient library.

This feature request is to support Amazon Cognito's token refresh behavior.

Cognito's token endpoint returns a `refresh_token` as expected when the `grant_type` is `authorization_code`, but it does not return a `refresh_token` when the grant_type is `refresh_token` ([Cognito reference](https://docs.aws.amazon.com/cognito/latest/developerguide/token-endpoint.html#post-token)).

The library currently expects the token response during refresh to always include the `access_token` and `refresh_token`, meaning that refreshing the token with Cognito can only be performed once, after which the `refresh_token` is undefined ([library code reference](https://github.com/soofstad/react-oauth2-pkce/blob/0a2d0ae77e86ed4be29b8c93d4017e4e9ad9d59b/src/AuthContext.tsx#L98)).

Thanks for the consideration.

### Basic Example

An example configuration flag could allow retaining the existing unexpired refresh token.

### Drawbacks

Cognito's token endpoint behavior is admittedly atypical.

**Comment by soofstad** [comment]
Hi, thanks for the report @rning 

Think this should be an easy change, which won't do much harm.
I'll get a fix out :slightly_smiling_face:
