### ISSUE TITLE
💡 [FEATURE] - Option in login()-function to not redirect, but instead do it in an iframe or popup

### ISSUE THREAD

**Issue by soofstad** [soofstad/react-oauth2-pkce#147]
### Summary

Scenario

1. The user has already logged in (has a cookie from the IDP)
2. The user need a new token with a different claim than the one configured in authConfig

### Basic Example

```jsx
<Button onClick={()=>login(mode='iframe', extraParams={"scope": "oldClaim newClaim")}>
```

### Drawbacks

none

### Reference Issues

See discussion https://github.com/soofstad/react-oauth2-pkce/discussions/146

**Comment by sebastianvitterso** [comment]
Just a comment on this one: If you use the popup functionality, then any `postLogin` callback will be called in that window, not in the main window. 
That's a caveat with the current implementation that one should be aware of.
