### ISSUE TITLE
Cover React 18 in the dependencies

### ISSUE THREAD

**Issue by idrm** [soofstad/react-oauth2-pkce#15]
Is there a reason why the latest release of `react-oauth-pkce` (1.4.0) has React dependencies (`react` and `@types/react`) that are versioned to not include v18?

**Comment by soofstad** [comment]
No reason. Just an oversight. 
Thank you pointing this out, much appreciated :smile:  

It's resolved by this commit; https://github.com/soofstad/react-oauth2-pkce/commit/90117b6bb42abf5d25d0075d88f84a7c8beb9c48

Version "1.4.1" is out on npmjs.com, and contains this fix.

**Comment by idrm** [comment]
Thanks for the library!
