### ISSUE TITLE
💡 [REQUEST] - Enhance Logout Functionality

### ISSUE THREAD

**Issue by kleysonfiretail** [soofstad/react-oauth2-pkce#156]
### Summary

The `react-oauth2-code-pkce` library currently lacks some functionalities that are common in similar libraries like `auth0-react`, which affects developers transitioning between these libraries. To bridge this gap, I propose the following enhancements:

- **PostLogout Callback**: A callback function that is triggered after the logout process completes.
- **Additional Parameters for logOut()**: Allow passing additional parameters to the logOut() method, akin to the login() method.
- **LogoutInProgress State**: A new state indicator to signify when a logout operation is in progress, enhancing UI responsiveness.

### Basic Example

Here are some basic examples of how these features could be implemented:

### PostLogout Callback Example:
```javascript
const authConfig: TAuthConfig = {
 // ... //
  postLogout: () => {
    console.log("Logout completed!");
    // Additional cleanup actions can be performed here
  }
};
```

### Additional Parameters for logOut() Example:
```javascript
const additionalParameters = {
  returnTo: '/home',
  customParam: 'value'
};
logOut(additionalParameters);
```

### LogoutInProgress State Example:
```javascript
const { logoutInProgress } = useAuth();

if (logoutInProgress) {
  return <div>Logging out...</div>;
}

```

### Drawbacks

**Complexity**: Introducing these features could increase the complexity of the library's API, potentially making it harder to maintain and understand.

**Scope Creep**: Each new feature could lead to requests for more similar features, potentially diverting focus from the core functionality of the library.

**Performance**: Adding more features, especially state management like logoutInProgress, might impact the performance if not implemented efficiently.

**Comment by soofstad** [comment]
Hi @kleysonfiretail 
Thank you for the suggestions.
I think these are reasonable requests. Params to the `login()` is something I have though of doing for some time, just never heard anyone actually missing it.
PostLogoutCallback is also a nice feature. Easy enough to add, and fits well with the existing callbacks pattern.

Not sure how you would use "LogoutInProgress", as it is a synchronous function, with no state and redirect back and fourth involved. If you could give an example for when you would need this to help me understand, that would be great :slightly_smiling_face:

**Comment by soofstad** [comment]
Closing this in favor of the other 2 issues
