### ISSUE TITLE
Bug: Error: "state" value received from authentication server does no match client request. Possible cross-site request forgery

### ISSUE THREAD

**Issue by MeKo-Christian** [soofstad/react-oauth2-pkce#177]
I got the error: `"state" value received from authentication server does no match client request. Possible cross-site request forgery` but when I look into the code it seems that there is a compare between null (as loadedState is null and receivedState is ""). This is in Firefox. Maybe the behavior is different on Firefox

## Steps To Reproduce

We have a custom identity provider, so it might only be related to this own identity provider, but the steps are very simple

1. Login (don't pass any state)
2. See error in console

## The current behavior

An error is shown

## The expected behavior

No error is shown since both values are more or less equally empty. Probably a warning could be printed to state that a state should be set.

If I set a state (even a simple one), it works like a charm.

**Comment by soofstad** [comment]
Hi, thanks for reporting.
Could you post the auth and token requests and all their parameters?
If you are not posting a state, then you should not get a empty sting back, I would consider that a identity provider bug. "More or less equal" is not really good enough when working with security related values :stuck_out_tongue:  

If that is the case, I would just add a state to the request, it's recommended anyway.

**Comment by MeKo-Christian** [comment]
For our purpose we have added a state. It's just a dummy state, but it stops the browser from complaining. And we want to use this state in the future anyway.
