### ISSUE TITLE
Bug: refreshToken does not refresh a token properly

### ISSUE THREAD

**Issue by MeKo-Christian** [soofstad/react-oauth2-pkce#185]
## Steps To Reproduce

1. Let the access token run out, but delete the refresh token server-side (and ensure it throws a 404 in that case)
2. Reload the website, now causing a 404 error resulting in a normal error and no `handleExpiredRefreshToken` triggering.

## The current behavior

`handleExpiredRefreshToken` is not triggered. A normal error is thrown

## The expected behavior

`handleExpiredRefreshToken` or any specific error is thrown or there is some way to do distinct between both errors.

**Comment by soofstad** [comment]
Hi @MeKo-Christian 
I do not regard this as a bug.
If the server can not find the refresh token in question, that is an error, and should not happen, the bug is in the server.
The library, and the RFC specifications, states that the auth server should return a 400 when a token refresh fails.
