### ISSUE TITLE
💡 [REQUEST] - Extract login method to config

### ISSUE THREAD

**Issue by Myks92** [soofstad/react-oauth2-pkce#194]
### Summary

In `AuthContext` has function `logIn` this uses method default `redirect` 
https://github.com/soofstad/react-oauth2-pkce/blob/b7980288083e99c1b751a2bbae41efc4b94d64cd/src/AuthContext.tsx#L88

Please extract this setting in config so that we can configure it. 

In my application, it is necessary to use the popup method, however, I cannot override this everywhere, since there are calls inside the application. 

My problem arises when the refresh token expires, then the `logIn` function is called already with the `refresh` method.
For example, here:

https://github.com/soofstad/react-oauth2-pkce/blob/b7980288083e99c1b751a2bbae41efc4b94d64cd/src/AuthContext.tsx#L136

I would like to call it like this: 
```js
function handleExpiredRefreshToken(initial = false) {
        // If it's the first page load, OR there is no sessionExpire callback, we trigger a new login
        if (initial)
            return logIn(undefined, undefined, "popup");
        // TODO: Breaking change - remove automatic login during ongoing session
        if (!config.onRefreshTokenExpire)
            return logIn(undefined, undefined, "popup");
        config.onRefreshTokenExpire({
            login: logIn,
            logIn,
        });
    }
  ```
the first condition cannot be redefined in any way, the second one can be used like this: 

```js
const authConfig: TAuthConfig = {
  onRefreshTokenExpire: (event: TRefreshTokenExpiredEvent) => event.logIn(undefined, undefined, "popup"),
}
```
I can also suggest removing the first condition. As a result, the second one will work, which we can override from the configuration

My auth config:

```js
const authConfig = {
  clientId: "01",
  authorizationEndpoint: "auth/authorization",
  tokenEndpoint: "https://example.ru/oauth2/token",
  redirectUri: window.location.origin + "/auth/callback/test",
  logoutEndpoint: "auth/logout",
  onRefreshTokenExpire: (event: TRefreshTokenExpiredEvent) => event.logIn(undefined, undefined, "popup"),
  autoLogin: false,
  state: `${Math.random().toString(36).substring(7)}_${Date.now()}`,
  scope: "offline openid",
} satisfies TAuthConfig;
```

### Basic Example

```js
type TAuthConfig = {
 loginMethod: 'popup' | 'refresh'
}
```

### Drawbacks

The authorization method cannot be controlled

**Comment by soofstad** [comment]
Think this is a reasonable request.
My assumption was that for the first page load, a popup would not be necessary. Out of curiosity, _why_ do you need a popup for the first login?

**Comment by Myks92** [comment]
I'm development an add-on for [Office Word](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart-yo) and there's a built-in browser. If I use a redirect, it opens an external browser, which is why I can't intercept the oauth 2 server response and log in.

> Think this is a reasonable request. My assumption was that for the first page load, a popup would not be necessary. Out of curiosity, _why_ do you need a popup for the first login?

I'm development an add-on for [Office Word](https://learn.microsoft.com/en-us/office/dev/add-ins/quickstarts/word-quickstart-yo) and there's a built-in browser. If I use a redirect, it opens an external browser, which is why I can't intercept the oauth 2 server response and log in.

**Comment by Myks92** [comment]
@soofstad, thanks! Can you tell me when you plan to make this functionality and release a version?

**Comment by soofstad** [comment]
If you feel up for it, please go ahead a make a pull-request with the required changes.
If not, I will probably find time in the next few weeks :slightly_smiling_face:
