### ISSUE TITLE
Feature: Option to disable "auto login"

### ISSUE THREAD

**Issue by soofstad** [soofstad/react-oauth2-pkce#20]
For some cases, automatically logging in on page load might not be suitable.
There should be a option to set `loginOnPageLoad: false`.

The `login()` function also needs to be exported by the \<AuthContext\> so manual login is possible.

**Comment by soofstad** [comment]
closed with https://github.com/soofstad/react-oauth2-pkce/commit/bb07098acaa0fb1adb4c191d904d7db02ab6eb92

**Comment by fujale** [comment]
This enhancement is not really working. Nothing happens when we tap on the CTA button.

**Comment by soofstad** [comment]
Hi,
Thank you for reporting any issues.
Are you using the `autoLogin: false` option?
And trying to login with a button calling the `login`function like this `<button onClick={() => login()}>Login</button>`?

If this did not solve it, could you upload that code that is not working for you?
