### ISSUE TITLE
Bug: autoLogin is false, but still invokes logIn upon page load and stored tokens are expired

### ISSUE THREAD

**Issue by robmatesick** [soofstad/react-oauth2-pkce#202]
I have a scenario where I do not want to do not want to do any automatic login to occur, unless the user initiates it (e.g. button click).  As such in my authConfig I have `autoLogin: false`.  

However, when the locally-stored access & refresh tokens are both expired and the user reloads the page, I find that the library is invoking the `refreshAccessToken` function, and then invoking `handleExpiredRefreshToken(true)`, which then ultimately invokes `logIn(undefined, undefined, config.loginMethod)`.  This occurs even if I have `onRefreshTokenExpire` defined in my authConfig.

Is this intentional and I need to design my application around it, or should this be fixed in this library?  Or have I possibly made a mistake elsewhere?

Tested against version 1.22.1 (latest)

## Steps To Reproduce
1. In `authConfig` set `autoLogin: false` and `onRefreshTokenExpire: (event: any) => window.alert('Session is expired.`)` 
2. Use `logIn` to successfully authenticate and have it cache the access & refresh tokens
3.  Either let the access & refresh tokens expire, or forcefully set the values behind the current time via browser DevTools or through code.
4.  Reload the page.

## The current behavior
Upon initial page load, the library forces an automatic login when existing tokens are expired, even though we have `autoLogin: false`

## The expected behavior
Upon initial page load, the library indicates that the tokens are expired by exposing `token = undefined`, and does NOT perform an automatic login when we have `autoLogin: false`.  This would allow the developer to take advantage of configuring the `onRefreshTokenExpire` handler to do what they wish.

**Comment by soofstad** [comment]
Thanks for reporting @robmatesick 
Agree that this is a bug.
If `autoLogin: false` and `onRefreshTokenExpire: Function`, the library should never instantiate a login redirect.
Will get a fix out shortly :+1:
