### ISSUE TITLE
Bug: Logout does not log out on auth provider

### ISSUE THREAD

**Issue by rferreira98** [soofstad/react-oauth2-pkce#23]
## Steps To Reproduce

1. setup logoutEndpoint
2. use logOut()
3. watch storage being cleared
4. login()
5. Doesn't redirect to authprovider/login and auto logs in

## The current behavior

Currently doesn't "log out", only clears client side info but doesn't redirect to logout endpoint.

## The expected behavior

Should log out on server and client.

**Comment by soofstad** [comment]
Hi, thanks for reporting this bug. I will have a look at it as soon as I got some time on my hands.

Could you provide which URL(logout url) and auth provider you are experiencing this with?

**Comment by rferreira98** [comment]
Hi there 👋 

It's a custom auth provider. I noticed the redirectLogoutUrl is never used in your source code.
I'm using a not so good workaround which is basicly redirecting the user to the logout url after logging out.

**Comment by soofstad** [comment]
Thanks, yes I saw that as well :neutral_face: 

Will add that ASAP. Just to make sure. Your custom auth provider expects a POST request with the AUTHENTICATION header and no body right?

**Comment by soofstad** [comment]
Nevermind, with a bit more digging I found this; https://datatracker.ietf.org/doc/html/rfc7009#section-2.1

Which should be considered the only answer on how the `revoke`/`logout` feature should be handled.
