### ISSUE TITLE
Refresh Token returned as 401 

### ISSUE THREAD

**Issue by BKB503** [soofstad/react-oauth2-pkce#24]
I'm using ping federate as provider, when ever making a request with grant type as refresh token getting 401, reason Ping Federate is expecting client secret which I have configured as extra params, is it possible to pass the extra parameters in the refresh token request, like original request ?

**Comment by soofstad** [comment]
Extra parameters for refresh request could be added. But this is not the use case for it.
`client_secret` should never be added to a SPA React application, as the web client can not be trusted.

For auth providers requiring `client_secret`, a proxy auth api needs to be added.
You can see an example of this in the github example here; https://github.com/soofstad/react-oauth2-pkce/blob/main/examples/github-auth-provider/github-auth-proxy/api.py

You should remove the `client_secret` from your react code as soon as possible. And make it invalid if it might have leaked in some way.

closing this issue :slightly_smiling_face:

**Comment by BKB503** [comment]
Ok, still in development mode, it is completely in my control, I'm aware of it we don't need to pass it, Thank you
