### ISSUE TITLE
Feature: Add extra auth params for the authorization endpoint

### ISSUE THREAD

**Issue by matias-desanti** [soofstad/react-oauth2-pkce#25]
Amazon Cognito allows for two custom parameters at the time of sending the request to the authorization endpoint to specify the identity provider that will be used. These parameters are `identity_provider` and `idp_identifier` as described in their documentation https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html.

As of now the package allows for `extraAuthParams` at the [time of getting the tokens](https://github.com/soofstad/react-oauth2-pkce/blob/main/src/authentication.ts#L96) but not at the time of [getting the login url when using the /authorize endpoint](https://github.com/soofstad/react-oauth2-pkce/blob/main/src/authentication.ts#L24).

Is there any reason this is not supported or is it possible to enable `extraAuthorizationParams` that can be passed to the `/authorize` endpoint?

**Comment by soofstad** [comment]
Hi, thank you for you'r suggestion! 

I was not aware of any auth providers that had extra params for the auth request.
A goal for the library is to support as many providers as possible, and the solution you propose fits in well with the already existing `extraAuthParams` options pattern as you point out.

I will get to implementing this feature as soon as I can :)

**Comment by soofstad** [comment]
This was easy enough to add.

The feature has been merged in this PR if you are interested: https://github.com/soofstad/react-oauth2-pkce/pull/26

Note that some of the config params changed name as they were misleading. Old ones still work for backwards compatibility.

Available now in version 1.7.0

**Comment by matias-desanti** [comment]
That was quick! Thank you very much!
