### ISSUE TITLE
typescript error

### ISSUE THREAD

**Issue by KristianKjerstad** [soofstad/react-oauth2-pkce#3]
typescript complains about the initialized value of authcontext.

i think this can be fixed by initializing AuthContext on line 14 in AuthContext.tsx

change: export const AuthContext = createContext({})
to
export const AuthContext = createContext({token: "NONE"}) for example

![image](https://user-images.githubusercontent.com/69512295/162686092-ce22f054-3e2a-4820-884b-5c6428dc0d46.png)

**Comment by soofstad** [comment]
Hi @KristianKjerstad 
This version will resolve the issue :) 
https://github.com/soofstad/react-oauth2-pkce/releases/tag/v1.2.3
