### ISSUE TITLE
Error with Webpack bundler

### ISSUE THREAD

**Issue by patrup** [soofstad/react-oauth2-pkce#33]
when using the library in an SharePoint Framework Webpart with React the bundle fails with a Webpack error: 
./node_modules/react-oauth2-code-pkce/dist/AuthContext.js 77:19
```bash
Module parse failed: Unexpected token (77:19)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     function logOut() {
|         clearStorage();
>         if (config?.logoutEndpoint && refreshToken)
|             (0, authentication_1.redirectToLogout)(config, refreshToken);
|     }
 @ ./node_modules/react-oauth2-code-pkce/dist/index.js 4:20-44
```
any ideas?

**Comment by sebastianvitterso** [comment]
Have you attempted to search for the error code?

Just to begin with StackOverflow's first suggestions, maybe [this answer](https://stackoverflow.com/a/34975252/11192976) can help? It explains how to load es2015 (es6) JS files with babel, I assume something similar should work for this. 
If I'm understanding the error correctly, it might be the optional chaining that it's getting caught up on, which is a (relatively) new feature that might need loading.

**Comment by soofstad** [comment]
I think @sebastianvitterso is right. The `react-oauth2-pkce`-package is "compiled" from typescript to ES2020.
I'm not familiar with SharePoint Framework Webpart, but upgrading your node version should make it possible to run ES2020 withouth any need for transpiling and babel config.

**Comment by soofstad** [comment]
@patrup, I see that targeting ES2020 might have been a bit optimistic.
The latest version `v1.8.2` targets ES2015, think that should work for you.
Closing the issue.
