### ISSUE TITLE
Feature Request: Ability to override access token expire actions

### ISSUE THREAD

**Issue by rferreira98** [soofstad/react-oauth2-pkce#36]
Ability to override access token expire actions
## Steps To Reproduce

1.Login
2. Wait for token to expire
3. It logins automatically

## The current behavior
It logins automatically

## The expected behavior
It logins automatically, but would be nice to have the possibility to override this behavior and logout, for example.

**Comment by soofstad** [comment]
Hi, thank you for reporting this.
I see that the behaviour on this is not well documented. Will get that fixed.
But you can already control this if you provide a callback function to the `onRefreshTokenExpire` configuration parameter.

So the logic is:
If the 'refreshToken' expires, or a silent refresh fails, call the 'onRefreshTokenExpire`-calback, if that is undefined, redirect to login. 

You'd usually do something like this;
```javascript
 onRefreshTokenExpire: (event) => 
    window.confirm('Session expired. Refresh page to continue using the site?') && event.login()
```

A hot tip is that you can manually change values in localStorage to trigger some events for testing. The package listens for changes to localstorage and updates it's state when it changes.

**Comment by rferreira98** [comment]
Hi 👋🏽 

Will this workaround still work even if I'm not using refresh token?

**Comment by soofstad** [comment]
Yes, if there is no refresh_token this event will happen when the access_token expires.

**Comment by soofstad** [comment]
I assume the suggestion solution worked for you @rferreira98 
closing the issue :slightly_smiling_face:
