### ISSUE TITLE
Bug: Making multiple Token calls with same grant type

### ISSUE THREAD

**Issue by farhanmalhi-dbank** [soofstad/react-oauth2-pkce#39]
When i login, it makes two token call, with same request having same grant type: authorization_code

Sharing screen shots for reference

![Screenshot 2022-11-26 at 1 29 23 AM](https://user-images.githubusercontent.com/111366884/204052694-dfd8aa3c-844a-4152-a135-6a87aa436670.png)
![Screenshot 2022-11-26 at 1 29 12 AM](https://user-images.githubusercontent.com/111366884/204052697-eef89f97-a2a7-47b7-a66a-bcf8ce374c2b.png)

**Comment by farhanmalhi-dbank** [comment]
@soofstad  Just an update which i figured out, the cause of this is
```
root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);
```
i.e if we use React.StrictMode which makes react components render twice and due to this Token end point is called twice.
Please fix this 
Thanks

**Comment by soofstad** [comment]
This is how StrictMode works for react 18 at the moment. With no way of disabling it for specific components (ref: https://github.com/facebook/react/issues/16362).

Any suggestions to how this could be solved are welcome.

**Comment by farhanmalhi-dbank** [comment]
@sebastianvitterso Yes, i agree it only happens in development mode.

**Comment by sebastianvitterso** [comment]
Good to verify! I don't think there's anything this library can do to remedy this effect (considering it is a deliberate function of StrictMode). Feel free to close the issue, unless there's anything else.

**Comment by farhanmalhi-dbank** [comment]
@sebastianvitterso Yes, you are right on this. Lets just wait for any update on Strict mode and I am closing this issue. If later on i found any fix or any update beneficial for this issue. I'll post.
