### ISSUE TITLE
Incorrect logout redirect url

### ISSUE THREAD

**Issue by harmoney-ryanli** [soofstad/react-oauth2-pkce#40]
Hi there, can you please fix this issue, it should use logout redirect Url instead of redirect URL. 
https://github.com/soofstad/react-oauth2-pkce/blob/52d639e6ec43cfd18078875e889fcb0aec662fa3/src/authentication.ts#L110

**Comment by soofstad** [comment]
Thank you for reporting this. It was simple a blatant error.
Should be fixed now in #41 and available in version 1.8.3
