### ISSUE TITLE
Expose this method to support API based auth

### ISSUE THREAD

**Issue by harmoney-ryanli** [soofstad/react-oauth2-pkce#44]
Hi there, can you please expose this function as well, so that it can support the tokens retrieved via a middleware instead of getting token from Keycloak server directly. 
https://github.com/soofstad/react-oauth2-pkce/blob/3185e79c55e5806806ec8147dc3a61898fca6cb0/src/AuthContext.tsx#L92

**Comment by soofstad** [comment]
Hi, thanks for the suggestion. However I'm having a bit of a problem understanding why you would need this, and how it relates to the OAuth2 flow.

Could you please describe in a bit more detail? :slightly_smiling_face:

**Comment by harmoney-ryanli** [comment]
Hi @soofstad , thanks for the reploy. 
The scenario I'm trying to implement is that
1. I create a user with Keycloak admin REST API
2. Then I get the access token with Keycloak direct grant access API
3. This access token will be sent back to the front end
4. In front end, I plan to inject the access token into AuthProvider, so that it can help me to handle token expiration. I think the appropriate way of implementing it is to invoke `handleTokenResponse` function. 
I'm not sure if this is a common use case.

**Comment by soofstad** [comment]
Thanks you, now I understand a bit better.
I have never seen such a pattern before, but I'am a bit reluctant to include this as it does not seem to be a feature described in the OAuth2 spec.

Out of curiosity and to help me understand; why can't you let the library do the sign in and token acquisition?
Also, how are you able to do a secure call to the API without using keycloak to login?

An other approach you could consider is to update the localStorage directly. Like setting the tokens, expire time and so on. This will have the same effect as you describe.

**Comment by harmoney-ryanli** [comment]
Totally understand it. 
The Keycloak API call is via our own backend service, so the security is guaranteed. 
Thank you for your advice, that is what I'm currently using.
