### ISSUE TITLE
Feature: idTokenData new IAuthContext value

### ISSUE THREAD

**Issue by github-gael-soude** [soofstad/react-oauth2-pkce#47]
It could be great if we had idTokenData in the useContext.

Today I have to reprocess the idToken decoding inside my react code.
It adds a few complexity when it could be done easily directly in the library as for tokenData.

The decoded idToken can be used for example to display the groups of the logged user.

```
interface IAuthContext {
  // The access token. This is what you will use for authentication against protected API's
  token: string
  // An object with all the properties encoded in the token (username, email, etc.)
  tokenData?: TTokenData
  // Login the user
  login: () => void  
  // Logout the user from the auth provider
  logOut: () => void
  // Keeps any errors that occured during login or token fetching/refreshing. 
  error: string | null
  // The idToken, if it was returned along with the access token
  idToken?: string
  // An object with all the properties encoded in the ID token (username, groups, etc.)
  idTokenData?: TTokenData
  // If the <AuthProvider> is done fetching tokens or not. Usefull for controlling page rendering
  loginInProgress: boolean
}
```

**Comment by sebastianvitterso** [comment]
I don't have the domain knowledge on OAuth, nor do I know the fundamental differences between these two token types. I think @soofstad will have to answer this.

**Comment by soofstad** [comment]
Absolutely @github-gael-soude, the library already has the capability to decode JWT's, so adding this should be fairly simple.
 I think I wanted to keep the interfaces as small as possible in the beginning, but it has evolved into more of a swiss-army-knife with lots of options and features. And so it makes sense to add this.
 
 Are you willing/able to create a PR for this @github-gael-soude? :slightly_smiling_face:
