### ISSUE TITLE
Bug: The idTokenData is not set

### ISSUE THREAD

**Issue by albertwangnz** [soofstad/react-oauth2-pkce#49]
The idTokenData is not set.

## Steps To Reproduce

1. Get access token and id token

## The current behavior
1. {idToken} has value that can be parsed in JWT format
2. {idTokenData} shows nothing and {JSON.stringify(idTokenData, null, 2)} shows nothing

## The expected behavior
{JSON.stringify(idTokenData, null, 2)} should show the payload of the id token.

**Comment by soofstad** [comment]
Hi,
Can you please post your configuration?
Also, are you sure the access token is a valid JWT? You can try it out at pages like jwt.ms
And, are you receiving a id_token in the token request? Usually you need some special config on the provider, and a special scope for this.

**Comment by albertwangnz** [comment]
Hi @soofstad , thank you for your reply.

I created a fork of the project https://github.com/albertwangnz/react-oauth2-pkce-issue49, and you can see my change in the example `microsoft-auth-provider`. I use AWS Cognito as the auth provider.

As you can see in the screenshot below, idTokenData is empty but idToken is not, and I can manually parse idToken to an object with the data.

![Screenshot from 2022-12-20 08-32-29](https://user-images.githubusercontent.com/110079777/208505300-13150d96-9aff-4e6a-b9ec-0d0477da2b99.png)

**Comment by albertwangnz** [comment]
I just guess the issue might be missing of using `if (idToken) setIdTokenData(decodeJWT(idToken))` in the file below.

src/AuthContext.tsx

Line 195.

**Comment by anthony-vito** [comment]
I think he's right. The idToken data is decoded and assign on line 105 of the AuthContext when a login happens...... but there is another effect() that decodes the access token that starts on line 163..... What is the purpose of that effect() ?  An additional decode for both tokens might need to be placed in there.

They should both also obey the configuration "config.decodeToken" to decide on if token decoding happens at all.

**Comment by soofstad** [comment]
You are both absolutely right.
Seems I was a bit quick on the testing for the last version.

As it is now, we decode the idToken on a received token response, but not when loading the page when the idToken is already fetched.

Will get a fix for this ASAP.

**Comment by albertwangnz** [comment]
Really appreciate your so fast response :-)

**Comment by soofstad** [comment]
Issue resolved by 85744ec9eb4e9a67a1b9de85a5138d28fedc4492.

Version 1.9.1 is now available with this included.

**Comment by albertwangnz** [comment]
Tested and it works. Thanks!
