### ISSUE TITLE
Bug: When developing with <React.StrictMode> in React 18, will get an error because the same auth code is used twice

### ISSUE THREAD

**Issue by albertwangnz** [soofstad/react-oauth2-pkce#50]
With [Strict Mode](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state) starting in React 18, whenever a component mounts in development, React will simulate immediately unmounting and remounting the component.

As a result, the same auth code will be sent to the auth provider twice, and the second time will get an error.

As React document mentions, it requires components to be resilient to effects being mounted and destroyed multiple times.

## Steps To Reproduce

1. 
`root.render(
<React.StrictMode>
  <AuthProvider authConfig={authConfig}>
        <LoginInfo />
      </AuthProvider>
  </React.StrictMode>
);`

2. The error will appear

## The current behavior
The useEffect() in AuthProvider is fired twice, and the same auth code is sent to the auth provider twice.

## The expected behavior
The same auth code should not be sent to the auth provider twice.

Btw, I am not a front-end developer, so maybe my understanding of the error is not correct.

**Comment by soofstad** [comment]
Hi,
Thanks for reporting this.
The fact that the useEffect is triggered twice in React 18 w/strict mode is expected behaviour. As there is no support for fine grained control of where it should render twice or not.

Is this causing any issues for you, or is there only a failed network request in the background?
Because if it's only a error in dev you can safely ignore this.

**Comment by albertwangnz** [comment]
Hi @soofstad , thank you for your reply.

I agree with you that it is only an error in dev so we can safely ignore this.

The motivation that I create the issue. As I understand, in the future, React would like to add a feature that allows React to add and remove sections of the UI while preserving the state. And this requires components to be resilient to effects being mounted and destroyed multiple times. ([refer](https://reactjs.org/docs/strict-mode.html#ensuring-reusable-state))

However, the component `AuthProvider` is not resilient to effects being mounted and destroyed multiple times. Since the `AuthProvider` will send two token requests to the auth provider with the same auth code, the second request will get an error response.

So, my two cents is that logic could be added to `AuthProvider` to prevent more token requests to be sent with the same code.

Since I am not a frontend developer and just started learning recently, I am not sure my understanding is correct. My apologies if I am wrong.

**Comment by soofstad** [comment]
Thanks, it's a bit more nuanced that I first though.
I think you are right and on to something. I will need to read a bit more into this too see how best to handle it.

If anyone comes across this comment and have some insight I'd be happy too hear it :) 

Not sure when I will get the time to fix this yet. Might take a while.
