### ISSUE TITLE
Bug:  redirect uri and Logout

### ISSUE THREAD

**Issue by ghauri899** [soofstad/react-oauth2-pkce#55]
2 things.

1.Document mentions that redirect uri is supposed to be the location where auth should take user after user logs out. But after we log in, we are redirected to the "redirectUri"
2. I logout user using the logOut() function while having the logoutRedirect to some other path, but it still takes me to the "redirectUri"
3. Note: my xyz.com/logout which is my logout endpoint, it is not completely operational, but What I expect at the moment is that after clicking out, I should be redirected to xyz.com/logout.

Any thoughts about this

## Steps To Reproduce
Here is my authconfig
```typescript
const authConfig: TAuthConfig = {
  clientId: process.env.REACT_APP_CLIENT_ID || '',
  authorizationEndpoint:
    process.env.REACT_APP_OAUTH_AUTHORIZATION_ENDPOINT || '',
  tokenEndpoint: process.env.REACT_APP_TOKEN_ENDPOINT || '',
  redirectUri: 'http://localhost:3000/oauth/callback',
  scope: process.env.REACT_APP_SCOPE,
  autoLogin:false,
  postLogin: () => {
    window.location.replace('http://localhost:3000');
  },
  logoutEndpoint:'https://xyz.com/logout',
  logoutRedirect:'https://xyz.com/logout'
};
```
Cheers
Thanks.

**Comment by soofstad** [comment]
Thanks for reporting this. Will be looking into it as soon as I can

**Comment by soofstad** [comment]
> 1.Document mentions that redirect uri is supposed to be the location where auth should take user after user logs out. But after we log in, we are redirected to the "redirectUri"

Bad documentation. Fixed. Thanks for reporting :+1: 

> 2. I logout user using the logOut() function while having the logoutRedirect to some other path, but it still takes me to the "redirectUri"

How is your logout endpoint configured?
You might take note of the fact that the parameter that is posted to the API is not `logoutRedirect`, but `post_logout_redirect_uri`.


You can see how this in done in this piece of code:

```ts
export function redirectToLogout(
  config: TInternalConfig,
  token: string,
  idToken?: string,
  state?: string,
  logoutHint?: string
) {
  const params = new URLSearchParams({
    token: token,
    // TODO: Add config param for token type
    token_type_hint: 'refresh_token',
    client_id: config.clientId,
    post_logout_redirect_uri: config.logoutRedirect ?? config.redirectUri,
    ui_locales: window.navigator.languages.reduce((a: string, b: string) => a + ' ' + b),
    ...config.extraLogoutParameters,
  })
  if (idToken) params.append('id_token_hint', idToken)
  if (state) params.append('state', state)
  if (logoutHint) params.append('logout_hint', logoutHint)

  window.location.replace(`${config.logoutEndpoint}?${params.toString()}`)
```

**Comment by sebastianvitterso** [comment]
@ghauri899 Any further updates/info on this?

I'll close the issue for now, but feel free to provide further details and we can re-open it.
