### ISSUE TITLE
feature: implement `state` in code request

### ISSUE THREAD

**Issue by soofstad** [soofstad/react-oauth2-pkce#63]
Per idToken [spec](https://connect2id.com/products/server/docs/api/authorization), the client should send a `state` with the code request, and check that this is the same before using the code to redeem a token.

**Comment by burnedikt** [comment]
I also stumbled upon this as it's an official part of the [OAuth2 RFC](https://www.rfc-editor.org/rfc/rfc6749#section-4.1.1)

> state
         RECOMMENDED.  An opaque value used by the client to maintain
         state between the request and callback.  The authorization
         server includes this value when redirecting the user-agent back
         to the client.  The parameter SHOULD be used for preventing
         cross-site request forgery as described in [Section 10.12](https://www.rfc-editor.org/rfc/rfc6749#section-10.12).

This is super handy to keep all kinds of application state like e.g. the url that was accessed prior to starting the authorization. `react-oauth2-pkce` provides the `preLogin` and `postLogin` callbacks where the state can also be stored (e.g. in localstorage) but I guess having support for the `state` parameter would be just as good.
