### ISSUE TITLE
Bug: Opening the application multiple times will lead to `onRefreshTokenExpire` in all but one instance

### ISSUE THREAD

**Issue by burnedikt** [soofstad/react-oauth2-pkce#64]
If a user duplicates the tab / has multiple browser windows open with an application running `react-oauth2-pkce` and the token expires, both tabs will try to refresh the token automatically. However, only one of them will succeed, for the second attempt, the refresh token will already have been consumed and therefore the refreshing doesn't work. 

I am perfectly aware, this is likely an edge case, but it still generated quite some confusion among our users.

## Steps To Reproduce

1. Open a tab with a react application using react-oauth2-pkce and authenticate
2. Duplicate the tab
3. Wait until the token is close to expiration / until the lib will try to refresh the token
4. See one tab successfully refresh the token, the other one prompting the user about the expired token (executing `onRefreshTokenExpire`)

## The current behavior

I think this is related to the fact that tokens are stored in local storage which is shared across all tabs on the same domain. It's nice because the duplicated tab does not need to fetch a token on its own and can just use the one that's already in local storage but in the refresh case, it's odd. Basically, this is a race condition: Whichever instance of the application first attempts to refresh the token, will succeed and then cause all other instances to fail / prompt to reload the page.

## The expected behavior

From a user perspective, I would just expect the token to be silently refreshed of course - in all tabs. But on a more technical level, I am not sure how to best achieve it. It would either require cross-tabs communication or storing the tokens not in `localStorage` but some tab specific storage like `sessionStorage`.

**Comment by burnedikt** [comment]
This is also amplified if two tabs try to get a token at the same time. Since the code verifier will be the same for both, only one of them will succeed, the other fail.

**Comment by soofstad** [comment]
Hi, thanks for raising this issue. It's an interesting one.
I absolutely agree that this is something that should be fixed, and expected to work.
Not sure on how to go about it though, as `sessionStorage` has it's own drawbacks.
Will need to look into this a bit more. If you have any suggestions I'd be happy to hear about them :slightly_smiling_face:

**Comment by burnedikt** [comment]
As much as I think about it, the only options I can come up with is having the storage of tokens (and other state, like the PKCE verifier) bound to the browser tab (or "session") (e.g. using `sessionStorage`) or by making the tabs communicate with each other using some kind of IPC. 

The former goes at the expense of state and tokens being lost when the tab is closed, which arguably from a security-perspective can eben be considered a feature, after all it's not great to store sensitive access tokens in localStorage. But of course, from a user-perspective it basiyll means re-authenticating at least once a day. The latter sounds quite complicated to me and might even be browser-dependent (how can two tabs communicate and decide "who's in charge"). It also has a lot of edge-cases to cover like what happens if the main tab who's in charge of refreshing tokens is closed, who takes over next, etc. Don't think that's feasible and likely outside of the scope of this lib.

From that perspective, I would lean towards `sessionStorage` with maybe an optional feature to persist the token in localStorage and load it from there into sessionStorage as well (needs to be removed after it has been hydrated into the application state again, otherwise the problem again exists).

Also quickly thought about prefixing the keys in localstorage with something tab-specific. But in the end, this would be the same result as using `sessionStorage` as another tab on the next day would not have the same prefix as the one from yesterday, so the data wouldn't be accessible.

One way forward would also to let the user decide, basically implementing a strategy pattern on where to store tokens. If localstorage is not a problem from a security perspective and because user's don't duplicate the tabs, then it can be used, otherwise sessionStorage can be used. Could be a configuration options and the two storages even use the same API.

**Comment by soofstad** [comment]
I discussed this with another maintainer, and we think this can be _mostly_ solved by setting a `refreshInProgress`-flag when the first tab tries to refresh a token. The other tabs/windows will then do nothing, and just wait for the shared localStorage to be updated.

Will need the same strategy for when the session has expired.

We are working with an implementation now, and will need to test it thoughly to see if there are any edge cases this will not cover. The main problem will be; "What to do if the user aborts the main tab"...

**Comment by burnedikt** [comment]
Also, some thoughts:

- is local storage thread-safe so we don't run into a race condition where two tabs "lock" the refresh at the same time?
- how would this work in case the refresh fails? How are other tabs notified? Will they poll the local storage for an error that the main tab puts there?

**Comment by sebastianvitterso** [comment]
@soofstad @burnedikt #66 addresses the issue (partially?), feel free to test and comment.

**Comment by soofstad** [comment]
Version v1.12.1(3649eb97fa06dd2e0da08140cf2e284aed3a2d26) is now published, which should solve the issues described here.

Closing the issue. Feel free to reopen if you still experience any problems related to this :slightly_smiling_face:

**Comment by burnedikt** [comment]
Thanks guys, will do some testing over the next days. Appreciate the fast reaction times 🙏

**Comment by burnedikt** [comment]
Worth noting that with version 1.13.0, users can also opt to use `sessionStorage` instead of `localStorage` for the auth provider which nullifies this issue. See https://github.com/soofstad/react-oauth2-pkce/pull/71
