### ISSUE TITLE
Bug: session not ended if browser was closed

### ISSUE THREAD

**Issue by arumlv** [soofstad/react-oauth2-pkce#69]
logged in first time with ouath2 verification & shut the browser and second time takes me straight through.
no localstorage cleanup option on configuration.

## Steps To Reproduce

1. open page,  autologin with oauth2
2. close browser
3. open browser, open page, user was already logged

## The current behavior
open browser, open page, user was already logged

## The expected behavior
open browser, open page, ouath2 login must be started

**Comment by marat-spay** [comment]
browser google Chrome Version 111.0.5563.64

**Comment by arumlv** [comment]
browser google Chrome 111.0.5563.64
