### ISSUE TITLE
React peer dependency erro

### ISSUE THREAD

**Issue by DraconPern** [soofstad/react-oauth2-pkce#7]
Got a peer dependency error.  react@"17.0.2"  I think it needs to be ^18.1.0?  Was trying to install it on CRA, but it failed on resolve.

**Comment by soofstad** [comment]
Hi, I'm not able to replicate this, however you are right, it should not be a specific version, but a "version greater than".
The example app (found under `./examples/`) work, you could take a look at that.
Anyway, pushing this fix as version 1.2.4. Let me know if it works for you. :slightly_smiling_face:
