### ISSUE TITLE
💡 [REQUEST] - Enable separate decoding steps for token/id_token

### ISSUE THREAD

**Issue by tony19** [soofstad/react-oauth2-pkce#74]
### Summary

My OAuth provider uses `id_token` as the JWT instead of `token`, but `react-oauth2-code-pkce`'s `AuthContext` tries to decode `token` first, and fails immediately without getting to `id_token`:

https://github.com/soofstad/react-oauth2-pkce/blob/4ada57fbdc873606e1705a03a0e8e71e7c3bbf66/src/AuthContext.tsx#L121-L126

https://github.com/soofstad/react-oauth2-pkce/blob/4ada57fbdc873606e1705a03a0e8e71e7c3bbf66/src/AuthContext.tsx#L233-L239

If they were decoded separately, I could at least use `idTokenData`. My current workaround is to disable `decodeToken`, and parse `idToken` with my own decoder.

#### Option 1: Decode the tokens separately

```typescript
if (decodeToken) {
  try {
    setTokenData(decodeJWT(token))
  } catch (e) {
    setError((e as Error).message)
  }

  try {
    if (idToken) setIdTokenData(decodeJWT(idToken))
  } catch (e) {
    setError((e as Error).message)
  }
}
```

#### Option 2: Add a separate config flag to decode `idToken`

```typescript
if (decodeToken) {
  try {
    setTokenData(decodeJWT(token))
  } catch (e) {
    setError((e as Error).message)
  }
}
if (decodeIdToken) {
  try {
    if (idToken) setIdTokenData(decodeJWT(idToken))
  } catch (e) {
    setError((e as Error).message)
  }
}
``` 

#### Option 1's Drawbacks

It potentially performs unnecessary work trying to decode `token` when only `idToken` is needed.  If `token` decoding fails, an error is shown in the browser console, which could annoy developers.

#### Option 2's Drawbacks

It's extra code/config to handle.

**Comment by soofstad** [comment]
Hi Tony,
Thank you for reporting this.
I think your suggestions makes sense, and will try to find a solution as soon as I can :slightly_smiling_face:
