### ISSUE TITLE
Bug: Session ends within 10 minutes with React 17.

### ISSUE THREAD

**Issue by PauloStanize-NHT** [soofstad/react-oauth2-pkce#75]
Hey! I am using react 17 on my application and I noticed that after login, the ROCP_tokenExpire variable on localStorage has the right value of 1 hour, but the application will end the session within 10 minutes and navigate back to the authorization endpoint. 

Looks like `refreshAccessToken` method is using the stale values for tokenExpire and refreshTokenExpire, which is the default FALLBACK_EXPIRE_TIME. 
Refreshing the page after authentication seems to solve the problem. 
The option `tokenExpiresIn` doesn't work as well.

I was able to fix it locally by setting the dependencies to useEffect, but would like to confirm if this is the best approach.

https://github.com/soofstad/react-oauth2-pkce/blob/main/src/AuthContext.tsx#L182

```
useEffect(() => {
  interval = setInterval(() => refreshAccessToken(), 10000) // eslint-disable-line
  return () => clearInterval(interval)
}, [token, tokenExpire, refreshToken, refreshTokenExpire, refreshInProgress])
```

## Steps To Reproduce

1. Copy the sample project
2. Downgrade both react and react-dom to v17.0.0
3. Change the index.js render to use the old react dom render method:
```
ReactDOM.render(
  <>
    <div>
      <h1>Demo using the &apos;react-oauth2-code-pkce&apos; package</h1>
      <p>
        Github:{' '}
        <a href="https://github.com/soofstad/react-oauth2-pkce">https://github.com/soofstad/react-oauth2-pkce</a>
      </p>
      <p>
        NPM:{' '}
        <a href="https://www.npmjs.com/package/react-oauth2-code-pkce">
          https://www.npmjs.com/package/react-oauth2-code-pkce
        </a>
      </p>
    </div>
    <AuthProvider authConfig={softheonConfig}>
      <LoginInfo />
    </AuthProvider>
  </>,
  document.querySelector('#root')
)
```

## The current behavior
The session ends in 10 minutes

## The expected behavior
The session must least for 1 hour

**Comment by soofstad** [comment]
Hi @PauloStanize-NHT :wave: 
Thank you for reporting this bug.
I think your fix there is correct, except it should not need all those dependencies, good catch!
However, I dont see how the react or react-dom version should have any influence on this. Are you certain you did not get the same behaviour on react 18?

Anyhow, will get this fix in as soon as possible :)

**Comment by PauloStanize-NHT** [comment]
Hey @soofstad, I only experienced this issue with react 17, although I too don't see any relations between versions and this bug. Thanks for your fast reply!

**Comment by soofstad** [comment]
I think you are right, [this](https://react.dev/blog/2022/03/29/react-v18#new-feature-automatic-batching feature) new feature (automatic batching) in react 18 would only update the interval once, after all the state had updated.

**Comment by PauloStanize-NHT** [comment]
So, I read about it, but my understanding was that the batching would avoid multiple rerenders if multiple values were set within a interval... I don't exactly see a connection here... I would blame the good and old closure context https://stackoverflow.com/a/70471506 but the fact that it worked on react 18 is really strange...
