### ISSUE TITLE
Unable to redirect to logout page without a refresh token

### ISSUE THREAD

**Issue by kimsekosen** [soofstad/react-oauth2-pkce#84]
I'm having issues with redirecting my app to the auth providers logout page. In short, my auth provider do not issue any refresh tokens (this is apparently the case in a Client Credentials Grant scheme). Hence, I'm blocked from redirecting by this line:

https://github.com/soofstad/react-oauth2-pkce/blob/949676328afb5d7d8287765dab0cb08844e45c41/src/AuthContext.tsx#L99
My auth provider uses OIDC. Per their spec ( https://openid.net/specs/openid-connect-rpinitiated-1_0.html#RPLogout ) a token/refresh token shouldn't be neccessary (though an id_token is recommended).

Thoughts?

**Comment by soofstad** [comment]
Hi @kimsekosen 
Thank you for reporting this.
You are absolutely right. For both the OIDC and OAuth2 spec, a refresh_token is not required to logout.
Will try to make a fix that makes the refresh_token optional :slightly_smiling_face:

**Comment by kimsekosen** [comment]
Thanks! Great package, keep up the good work! :)

**Comment by soofstad** [comment]
Should be resolved with https://github.com/soofstad/react-oauth2-pkce/commit/a24b456638f776b9ca8d53907330e129c1dd941e (version 1.13.3)
