### ISSUE TITLE
Bug: Auto login triggered when fetching tokens

### ISSUE THREAD

**Issue by daannet** [soofstad/react-oauth2-pkce#92]
Since [v1.13.4](https://github.com/soofstad/react-oauth2-pkce/releases/tag/v1.13.4) we've an issue that the auto login is triggered after returned and login is in progress. This causes an infinity loop authorizing and the fetchTokens call cancelled.

## Steps To Reproduce

1. Set autoConfig: true
2. Go to application, redirected to OAuth login
3. Enter details and return to React application
4. React application is trying to fetch tokens and login is called while fetching tokens

## The current behavior
Application loops infinity to authorize endpoint (autoLogin login()) and trying to fetch token 

## The expected behavior
No concurrent token fetch and auto login trigger

**Comment by soofstad** [comment]
closed by #93
