### ISSUE TITLE
Bug: Infinite loop using Microsoft Provider

### ISSUE THREAD

**Issue by wesley-monaro** [soofstad/react-oauth2-pkce#94]
Hi guys.

Using Microsoft as a login provider, after the login we have a infinite loop when the page is redirected, even using the "cleanURL" param as true.

## Steps To Reproduce

1. Set https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize/ as authorizationEndpoint
2. Set https://login.microsoftonline.com/organizations/oauth2/v2.0/token as tokenEndpoint

Configure your own clientId, and after the login you will see the infinite loop refresh, between microsoft and your application.

**Comment by wesley-monaro** [comment]
The problem was resolved adding !loginInProgress in the IF statement, file AuthContext.tsx, line 225:

<img width="509" alt="image" src="https://github.com/soofstad/react-oauth2-pkce/assets/120019901/6260369f-c0f2-49b8-b0f4-1ebf82dccd44">

**Comment by soofstad** [comment]
Hi @wesley-monaro 
Thank you for reporting this :slightly_smiling_face: 
However, I belive this was fixed with PR #93, available in version 1.13.5.
Are you sure you are running this latest version?

**Comment by wesley-monaro** [comment]
Hey @soofstad 
Perfect, the problem was really solved on this PR. Using the 1.13.5 works fine.
Thank you so much.
