### ISSUE TITLE
can't remove scope from request

### ISSUE THREAD

**Issue by mbrinkl** [soofstad/react-oauth2-pkce#96]
Any reason scope cannot be removed from request? If undefined in config, it defaults to empty string.

https://github.com/soofstad/react-oauth2-pkce/blob/8acce0fd8eca03d95aeba5f6dc5b9b4e28c813f1/src/authConfig.ts#L14

**Comment by sebastianvitterso** [comment]
Is there any reason why you don't want this scope as part of the request? Feel free to elaborate your needs a bit more, and we'll look into it!

**Comment by mbrinkl** [comment]
For my purposes, I later realized i could send scope as 'read write' and have same result as sending no scope. So this doesn't matter as much for me anymore.

I did find another similar issue on another oauth repo though, up to you what you want to do. https://github.com/mulesoft-labs/js-client-oauth2/issues/98

**Comment by soofstad** [comment]
I agree that this should be considered a bug. For most servers the current behaviour does not cause any issues, but I see no reason why we shouldn't adhere to the spec on this.
Will you look into a fix @sebastianvitterso ? If not I can have a look in a few weeks time. Also, for some badly implemented servers, empty string should be considered a valid value that will be sent from client.

**Comment by jwill490** [comment]
@soofstad in my case, I'm accessing a Forgerock auth server that throws a 400 error when "scope" is in the request for the auth token. Is there anyway to disable the scope parameter for only the auth token request, while leaving it in the auth code request? 

I imagine this is an edge case, but please let me know if you have any suggestions.

**Comment by LucasFrecia** [comment]
We are experiencing the same issue.  We have an openam configuration which needs the scope removed from this request, here is the example response:

```
error: "invalid_request"
error_description: "Scope parameter is not supported on an authorization code access_token exchange request. Scope parameter should be supplied to the authorize request."
```
