### ISSUE TITLE
can't navigate back after calling login

### ISSUE THREAD

**Issue by mbrinkl** [soofstad/react-oauth2-pkce#97]
could there be an option to change this to `href =` instead of `replace` ?

I am using autoLogin: false in my config, and navigating to the login on a button click. I'd like to be able to navigate back using browser back button after opening login page.

https://github.com/soofstad/react-oauth2-pkce/blob/8acce0fd8eca03d95aeba5f6dc5b9b4e28c813f1/src/authentication.ts#LL40C24-L40C24

**Comment by sebastianvitterso** [comment]
I don't see any security-reason why this wouldn't be alright, and after testing quickly, it feels better to be able to hit the back-button on my mouse to go back to before the login. I'll make a PR.

**Comment by soofstad** [comment]
The preferred behaviour is not obvious here. What should happen if the auth server has cookies stored, and the login happens instantly? Would seem weird for the user to navigate back to a login page then.
